include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - lib/firebase_options.dart

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    sort_constructors_first: false
