targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/**/models/**
      json_serializable:
        options:
          any_map: true
          explicit_to_json: true
        generate_for:
          - lib/**/models/**
