name: breathe_with_me
description: Breathe With Me is an app with breathwork practices that can help you change your mental, emotional, and physical states depending on what your needs at the moment are - you can become more energized, balanced, relaxed or prepare yourself for a deep night's sleep.

publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.9
  collection: 1.18.0
  # ------------------------
  # Firebase
  firebase_core: 2.20.0
  firebase_analytics: 10.6.2
  firebase_crashlytics: 3.4.2
  cloud_firestore: 4.12.1
  firebase_storage: 11.4.0
  firebase_auth: 4.12.0
  cloud_functions: 4.5.2
  firebase_messaging: 14.7.2
  firebase_remote_config: 4.3.2
  fake_cloud_firestore: 2.4.6
  # ------------------------
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  app_tracking_transparency: ^2.0.4
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  audio_service: ^0.18.12
  rxdart: ^0.27.7
  path_provider: ^2.1.2
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.4
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path: ^1.8.3
  flutter_animate: ^4.4.0
  url_launcher: ^6.2.3
  timezone: ^0.9.2
  flutter_local_notifications: ^16.3.1+1
  uuid: ^4.3.3
  app_settings: ^5.1.1
  purchases_flutter: ^6.16.1
  fast_noise: ^2.0.0
  shared_preferences: ^2.2.2
  flutter_shaders: ^0.1.2
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/i18n/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 300
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
  shaders:
    - assets/shaders/player_animation.glsl
