name: breathe_with_me
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.9
  collection: 1.18.0
  # ------------------------
  # Firebase
  firebase_core: ^2.19.0
  firebase_analytics: ^10.6.1
  firebase_crashlytics: ^3.4.1
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.3.1
  firebase_auth: ^4.11.1
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  # ------------------------
  app_tracking_transparency: ^2.0.4
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  audio_service: ^0.18.12
  rxdart: ^0.27.7
  path_provider: ^2.1.1
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.3
  cached_network_image: ^3.3.0
  flutter_riverpod: ^2.4.7
  hooks_riverpod: ^2.4.7
  objectbox: ^2.3.1
  objectbox_flutter_libs: ^2.3.1
  path: ^1.8.3
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  objectbox_generator: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/i18n/
    - assets/icons/
    - assets/audio/
  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 300
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
