name: breathe_with_me
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^11.1.4
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.7
  collection: 1.17.2
  # ------------------------
  # Firebase
  firebase_core: ^2.18.0
  firebase_analytics: ^10.6.0
  firebase_crashlytics: ^3.4.0
  cloud_firestore: ^4.10.0
  # ------------------------
  audioplayers: ^5.2.0
  rxdart: ^0.27.7
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/i18n/
    - assets/icons/
    - assets/audio/
    - assets/lottie/
  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 300
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
