name: breathe_with_me
description: Breathe With Me is an app with breathwork practices that can help you change your mental, emotional, and physical states depending on what your needs at the moment are - you can become more energized, balanced, relaxed or prepare yourself for a deep night's sleep.

publish_to: "none"

version: 2.1.0+9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  go_router: ^14.2.1
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.10+1
  collection: 1.18.0
  # ------------------------
  # Firebase
  firebase_core: 2.31.0
  firebase_analytics: 10.10.5
  firebase_crashlytics: 3.5.5
  cloud_firestore: 4.17.3
  firebase_storage: 11.7.5
  firebase_auth: 4.19.5
  cloud_functions: 4.7.4
  firebase_messaging: 14.9.2
  firebase_remote_config: 4.4.5
  fake_cloud_firestore: 2.5.1
  # ------------------------
  # Audio
  just_audio: ^0.9.38
  audio_session: ^0.1.19
  audio_service: ^0.18.13
  # ------------------------
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  app_tracking_transparency: ^2.0.5
  rxdart: ^0.27.7
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_hooks: ^0.20.5
  cached_network_image: ^3.3.1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path: ^1.9.0
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.0
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.1
  uuid: ^4.4.2
  app_settings: ^5.1.1
  shared_preferences: ^2.2.3
  flutter_shaders: ^0.1.2
  flutter_native_splash: ^2.4.0
  logger: ^2.3.0
  uni_links: ^0.5.1
  package_info_plus: 8.0.0
  wakelock_plus: 1.2.5
  purchases_flutter: ^6.30.2
  adaptive_dialog: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.10
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/i18n/
    - assets/icons/

  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 300
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oxygen-Regular.ttf
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
  shaders:
    - assets/shaders/player_animation.glsl
