// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwIpAXuiZIqbseUH1fpqhXLxcO1sbesrs',
    appId: '1:847416864961:android:d8420b660263ff10cb6440',
    messagingSenderId: '847416864961',
    projectId: 'bwithmedev',
    storageBucket: 'bwithmedev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC0YdD9Gp2DzRcgn_PAHNGPE2jCsJUg3A',
    appId: '1:847416864961:ios:a631b5228db0cf4fcb6440',
    messagingSenderId: '847416864961',
    projectId: 'bwithmedev',
    storageBucket: 'bwithmedev.appspot.com',
    androidClientId:
        '847416864961-d0era2vo7egt5tuo35ap75a9kic7h2vm.apps.googleusercontent.com',
    iosClientId:
        '847416864961-nru6bh3uoavn8ea82cbm20aboed5m46p.apps.googleusercontent.com',
    iosBundleId: 'com.dobry.breathewithme',
  );
}
