// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/entities/bloc_state_entity.dart';
import 'database/entities/download_task_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 3443719293430748280),
      name: 'DownloadTaskEntity',
      lastPropertyId: const IdUid(7, 6058418397631871564),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2470138575464844556),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(3, 7796491158390526320),
            name: 'downloadedBytes',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 8256646648292446768),
            name: 'totalBytes',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3033313459825828610),
            name: 'url',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4630339859809275241),
            name: 'filePath',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 6058418397631871564),
            name: 'taskId',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 7122328718598964543),
      name: 'BlocStateEntity',
      lastPropertyId: const IdUid(4, 31987012256534505),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5788823921696499688),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(3, 2205848117698045990),
            name: 'json',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 31987012256534505),
            name: 'key',
            type: 9,
            flags: 2080,
            indexId: const IdUid(4, 5744209523469708764))
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 7122328718598964543),
      lastIndexId: const IdUid(4, 5744209523469708764),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [
        3843725167060959184,
        2357976250776051976,
        604298339150924081
      ],
      retiredPropertyUids: const [7502259553311868414, 5553752235591540271],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    DownloadTaskEntity: EntityDefinition<DownloadTaskEntity>(
        model: _entities[0],
        toOneRelations: (DownloadTaskEntity object) => [],
        toManyRelations: (DownloadTaskEntity object) => {},
        getId: (DownloadTaskEntity object) => object.id,
        setId: (DownloadTaskEntity object, int id) {
          object.id = id;
        },
        objectToFB: (DownloadTaskEntity object, fb.Builder fbb) {
          final urlOffset = fbb.writeString(object.url);
          final filePathOffset = fbb.writeString(object.filePath);
          final taskIdOffset = fbb.writeString(object.taskId);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(2, object.downloadedBytes);
          fbb.addInt64(3, object.totalBytes);
          fbb.addOffset(4, urlOffset);
          fbb.addOffset(5, filePathOffset);
          fbb.addOffset(6, taskIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final taskIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final urlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final filePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final downloadedBytesParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final totalBytesParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final object = DownloadTaskEntity(
              taskId: taskIdParam,
              url: urlParam,
              filePath: filePathParam,
              downloadedBytes: downloadedBytesParam,
              totalBytes: totalBytesParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    BlocStateEntity: EntityDefinition<BlocStateEntity>(
        model: _entities[1],
        toOneRelations: (BlocStateEntity object) => [],
        toManyRelations: (BlocStateEntity object) => {},
        getId: (BlocStateEntity object) => object.id,
        setId: (BlocStateEntity object, int id) {
          object.id = id;
        },
        objectToFB: (BlocStateEntity object, fb.Builder fbb) {
          final jsonOffset = fbb.writeString(object.json);
          final keyOffset = fbb.writeString(object.key);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(2, jsonOffset);
          fbb.addOffset(3, keyOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final keyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final jsonParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = BlocStateEntity(key: keyParam, json: jsonParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [DownloadTaskEntity] entity fields to define ObjectBox queries.
class DownloadTaskEntity_ {
  /// see [DownloadTaskEntity.id]
  static final id =
      QueryIntegerProperty<DownloadTaskEntity>(_entities[0].properties[0]);

  /// see [DownloadTaskEntity.downloadedBytes]
  static final downloadedBytes =
      QueryIntegerProperty<DownloadTaskEntity>(_entities[0].properties[1]);

  /// see [DownloadTaskEntity.totalBytes]
  static final totalBytes =
      QueryIntegerProperty<DownloadTaskEntity>(_entities[0].properties[2]);

  /// see [DownloadTaskEntity.url]
  static final url =
      QueryStringProperty<DownloadTaskEntity>(_entities[0].properties[3]);

  /// see [DownloadTaskEntity.filePath]
  static final filePath =
      QueryStringProperty<DownloadTaskEntity>(_entities[0].properties[4]);

  /// see [DownloadTaskEntity.taskId]
  static final taskId =
      QueryStringProperty<DownloadTaskEntity>(_entities[0].properties[5]);
}

/// [BlocStateEntity] entity fields to define ObjectBox queries.
class BlocStateEntity_ {
  /// see [BlocStateEntity.id]
  static final id =
      QueryIntegerProperty<BlocStateEntity>(_entities[1].properties[0]);

  /// see [BlocStateEntity.json]
  static final json =
      QueryStringProperty<BlocStateEntity>(_entities[1].properties[1]);

  /// see [BlocStateEntity.key]
  static final key =
      QueryStringProperty<BlocStateEntity>(_entities[1].properties[2]);
}
